account_type_need_name:
  ar: "ar"
  ap: "ap"

cash_types:
  bank: "bank"
  safe: "safe"

voucher_types:
  civ: "civ"
  cov: "cov"

company:
  branch: "PNP"

confirm_modal_types:
  has_children: "has_children"
  active: "active"
  inactive: "inactive"
  destroy: "destroy"
